apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/jenkins/hapi-days:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/jenkins/hapi-days:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: hapi-days
        chartPath: charts/hapi-days
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/jenkins/hapi-days'
          image.tag: '{{.DIGEST_HEX}}'
